pos: {x: 6.0, y: 6.0, z: 10.0} 
vel: {x: 3.0, y: 3.0, z: 6.0}
rot: {x: 0.3, y: 0.3, z: 0.2}
ang: {x: 0.05, y: 0.05, z: 0.0004}
#xi: {x: 16.5, y: 16.5, z: 10.5}
#omg: {x: 6.8, y: 6.8, z: 3.0}

xi: {x: 16.0, y: 16.0, z: 16.0}
omg: {x: 6.7, y: 6.7, z: 3.1}